### ISSUE TITLE
No implementation for method log on channel flutter_fimber

### ISSUE THREAD

**Issue by dspells** [magillus/flutter-fimber#103]
I just upgraded to Flutter 2.0.1/dart 2.12.0
I updated to flutter_fimber: ^0.6.1
I have lost all logging and I get the following error message repeatedly running on an Android device or an Android emulator.

`E/flutter ( 9268): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method log on channel flutter_fimber)
E/flutter ( 9268): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 9268): <asynchronous suspension>
E/flutter ( 9268): 
`

I did flutter clean / flutter pub upgrade.
I tried pouring over the documentation for flutter 2 to see if I need to change my project in some way. I did not find any guides on changes that I need to make.

Thanks in advance for any help you can give on this issue.

**Comment by magillus** [comment]
Sure thing - thank you for reporting it - I try to take care of it this evening.

**Comment by dspells** [comment]
Thanks for the quick fix. I tested it this morning and it's working great.
