### ISSUE TITLE
Flutter 2.0.2 without NullSafety (flutter_fimber: 0.6.2)

### ISSUE THREAD

**Issue by raegtime** [magillus/flutter-fimber#105]
After upgrading my app to Flutter 2.0.2 (without nullSafety) i get the following error while building for android (ios works fine):

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.

Android resource linking failed
  /Users/FOO/projects/BAM/energielabel_app/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:17: AAPT: error: unexpected element <queries> found in <manifest>.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org
BUILD FAILED in 10s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_fimber...
Running Gradle task 'assembleAarRelease'...

e: /Users/FOO/.pub-cache/hosted/pub.dartlang.org/flutter_fimber-0.6.2/android/src/main/kotlin/com/magillus/flutterfimber/FlutterFimberPlugin.kt: (3, 28): Unresolved reference: NonNull
e: /Users/FOO/.pub-cache/hosted/pub.dartlang.org/flutter_fimber-0.6.2/android/src/main/kotlin/com/magillus/flutterfimber/FlutterFimberPlugin.kt: (20, 38): Unresolved reference: NonNull
e: /Users/FOO/.pub-cache/hosted/pub.dartlang.org/flutter_fimber-0.6.2/android/src/main/kotlin/com/magillus/flutterfimber/FlutterFimberPlugin.kt: (25, 32): Unresolved reference: NonNull
e: /Users/FOO/.pub-cache/hosted/pub.dartlang.org/flutter_fimber-0.6.2/android/src/main/kotlin/com/magillus/flutterfimber/FlutterFimberPlugin.kt: (25, 59): Unresolved reference: NonNull
e: /Users/FOO/.pub-cache/hosted/pub.dartlang.org/flutter_fimber-0.6.2/android/src/main/kotlin/com/magillus/flutterfimber/FlutterFimberPlugin.kt: (51, 40): Unresolved reference: NonNull

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':compileReleaseKotlin'.

Compilation error. See log for more details

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org
BUILD FAILED in 5s

Exception: The plugin flutter_fimber could not be built due to the issue above.

**Comment by magillus** [comment]
Thank you for reporting this.
Can you share flutter_fimber entry in pubspec.lock and pubspec.yaml files?

**Comment by mauriceraguseinit** [comment]
**pubspec.yaml**
flutter_fimber: 0.6.2

**pubspec.lock**
fimber:
    dependency: transitive
    description:
      name: fimber
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
flutter_fimber:
    dependency: "direct main"
    description:
      name: flutter_fimber
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.2"

**Comment by fredgrott** [comment]
I spotted something. Do both fimber and fimber-flutter versions have to match? as in that pubspec posted they do not.

**Comment by magillus** [comment]
no they do not need to match

**Comment by magillus** [comment]
https://pub.dev/packages/flutter_fimber was release - please double check on your project. ( Works on my machine ;-) )
