### ISSUE TITLE
Debug print without timestamp & colorize logs android studio support 

### ISSUE THREAD

**Issue by woogi-kang** [magillus/flutter-fimber#108]
Hello! Thanks for this amazing library!
This helps me a lot!

Is there any way to print the logs without timestamp?
and it seems I need to set my own settings to android studio to colorize the logs, but how?

Thank you again

**Comment by magillus** [comment]
Hello, thank you. I am glad you like it.

Yes, you can change custom formatting tree - see this test for example details:

https://github.com/magillus/flutter-fimber/blob/master/fimber/test/custom_format_test.dart

**Comment by woogi-kang** [comment]
Thank you so much for fast response! 

It would be great if you post this extending methods for customizing this package in the example in pub.dev so that 
others could see as well.

**Comment by magillus** [comment]
I will keep this issue open to remind me to do it, thank you for suggestion.

**Comment by magillus** [comment]
will be updated with next release: 
so far readme on github is reflecting this: CustomFormatTree
