### ISSUE TITLE
Migrate maven repository from JCenter to MavenCentral

### ISSUE THREAD

**Issue by temarez** [magillus/flutter-fimber#116]
[jcenter.bintray.com](https://jcenter.bintray.com/) will not be available since February 1st, 2022. See more info at [JCenter and Bintray is shutting down, what to do?](https://testfairy.com/blog/jcenter-and-bintray-is-shutting-down-what-to-do/)
This may cause inability of the project using flutter-fimber to be built on the clean environment.

Migration can be done by replacing `jcenter()` to `mavenCentral()` in these gradle files:
flutter_fimber/android/build.gradle
flutter_fimber/example/android/build.gradle

**Comment by magillus** [comment]
Thank you for brining that up.

**Comment by magillus** [comment]
Version 0.6.5 should fix this.

**Comment by temarez** [comment]
Thank you very much.
