### ISSUE TITLE
What's the reason for `ex` being dynamic?

### ISSUE THREAD

**Issue by luckyhandler** [magillus/flutter-fimber#126]
I'm wondering why `ex` is dynamic and not `Exception`. Can I pass any object to the api?
Would be happy about a clarification, thanks.

```dart
/// Logs [message] with log [level]
/// and optional [tag], [ex] (exception) [stacktrace]
void log(String level, String message,
  {String tag, dynamic ex, StackTrace stacktrace});
```

**Comment by magillus** [comment]
Hello,
Yes, it can be any object passed. Any class or Error or Exception based. 
You can `throw` any object at Dart and this signature of method will support it.
