### ISSUE TITLE
Support flutter 3

### ISSUE THREAD

**Issue by saharvx9** [magillus/flutter-fimber#128]
Pls Support flutter 3

**Comment by magillus** [comment]
I started doing the updates at: https://github.com/magillus/flutter-fimber/compare/main...upgrade.pluging

I need to verify if it works on iOS and update to new version

**Comment by magillus** [comment]
Unfortunate I wasn't able to complete this with tests and iOS platform plugin update is on hold, it was always normal console output on iOS - no big loss.
I suggest to just fimber or fimber_io only since flutter_fimber is plugin based package.

**Comment by magillus** [comment]
It should be resolved in 0.7.0 version published
