### ISSUE TITLE
FileTree - Add a file log tree that prints output to the file.

### ISSUE THREAD

**Issue by magillus** [magillus/flutter-fimber#21]
Discover how to do this in both flutter/dartvm environments

- define path to the file
- handle permission errors
- rolling file strategy is nice to have (time or size or both)
- file name and path pattern

**Comment by magillus** [comment]
Done:

* define path to the file
* rolling file strategy is nice to have (time or size or both)
* simple file name and path pattern

**Comment by magillus** [comment]
Add 
* Sometimes new line character is not created.

**Comment by neiljaywarner** [comment]
@magillus  this is neat; does this work on dartpub version?

**Comment by magillus** [comment]
yes, the `fimber` is dart only logging, `flutter_fimber` is flutter

**Comment by magillus** [comment]
bug fix should take care of: `Sometimes new line character is not created.`

only `create paths if the file's directory doesn't exists` left todo
