### ISSUE TITLE
Use `debugPrint` instead of just `print`

### ISSUE THREAD

**Issue by filipproch** [magillus/flutter-fimber#3]
As I see in source, you are using `print`, maybe worth it to use `debugPrint` (from Flutter) to avoid problems on Android?
https://flutter.io/docs/testing/debugging#print-and-debugprint-with-flutter-logs

**Comment by magillus** [comment]
Thank you for suggestion, I will update this package for now to use debugPrint.
In future I might migrate it a little;
My idea was to have base `fimber` for dart only (no flutter dependency), then plugins for `mobile-fimber` that would use native android/ios logging via channels.
