### ISSUE TITLE
Only last log gets outputted to file

### ISSUE THREAD

**Issue by ShawnRG** [magillus/flutter-fimber#30]
Hi,

After issuing a call on two different levels after each other, only the last log gets outputted to the file

```dart
Fimber.plantTree(TimedRollingFileTree(filenamePrefix: "/data/data/be.ifm.buildingviewerflutter/log_"));
Fimber.e("Crashing app", stacktrace: StackTrace.fromString("sdfsdfs"), ex: String);
Fimber.e("Crashing app", stacktrace: StackTrace.fromString("sdfsdfs"), ex: String);
Fimber.i("Running app");
```

File output:
`2019-03-09T14:13:51.887683	I main: Running app`

**Comment by magillus** [comment]
Thanks for reporting this, I saw the error before and I thought I fixed it.

What version did you used?

**Comment by magillus** [comment]
I was able to reproduce, my unit test "waited 100ms" between log entrees, on the append test.
I updated unit test and will work on fix.

**Comment by ShawnRG** [comment]
I fixed the issue by moving the IOsink up and closing the sink in after the done promise

**Comment by magillus** [comment]
Thanks for hint!
I was working today on solution with some buffering - but introduced subdir for tests and one of test still needs fix.
I will post PR soon.

**Comment by magillus** [comment]
published in [0.1.11]

**Comment by ShawnRG** [comment]
Amazing!

**Comment by magillus** [comment]
@ShawnRG Let me know if you run into log output issues, I was using DartVM on some project and used it but not anymore, so I do not have "live" environment for file logging.
