### ISSUE TITLE
iOS swift version issue?

### ISSUE THREAD

**Issue by neiljaywarner** [magillus/flutter-fimber#36]
Does this work on all versions of swift? We had an error about swift version..

**Comment by magillus** [comment]
@neiljaywarner Do you have stacktrace of the error?
Is this error during build or during runtime?

**Comment by neiljaywarner** [comment]
build time.
it says something about invalid swift version. Does it work for you?  (It is not me that gets the error - it is my iOS colleage but i need the project to build on iOS and this is the only thing right now that causes it to actually not build and run)

**Comment by magillus** [comment]
I didn't had time to fire up Mac this week, but I will look at it.

**Comment by magillus** [comment]
Hi @neiljaywarner 
I tested the example app and it works fine. 
note: Since I do not use mac daily I did upgrade flutter and some requirements for ios.

Can you run `flutter doctor` and post output?

**Comment by magillus** [comment]
Closing, can't reproduce and no response from author
