### ISSUE TITLE
I can't find the methodFimber.addTree,please update docs

### ISSUE THREAD

**Issue by AweiLoveAndroid** [magillus/flutter-fimber#48]
I can't find the methodFimber.addTree,please update docs.

```
void main() {
  Fimber.addTree(DebugTree());
  // app code here ...
}
```

**Comment by magillus** [comment]
Thanks, that is my next plan - for now use `Fimber.plantTree(...)`

**Comment by magillus** [comment]
updated documentation and closing ticket

thank you
