### ISSUE TITLE
FimberLog stopped logging messages and printing to the console

### ISSUE THREAD

**Issue by alexZaicev** [magillus/flutter-fimber#57]
Recently I`ve noticed that I`m not able to see any activity from my logging service (FimberLog for each class). I`ve checked the Logcat in Android Studio that filters are set correctly (checked without any filters), and  I still could not find any logs made from FimberLog.. 

This is how initialize the logger:

    FimberLog getLogger(dynamic obj) {
      if (obj == null) {
        return null;
      }
      final Type t = obj.runtimeType;
      return FimberLog(t.toString());
    }

> [√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-GB)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Android Studio (version 3.5)
> [√] Connected device (1 available)
> 
>
> fimber: ^0.3.2

**Comment by magillus** [comment]
Hello,
Sorry for delayed response - I must miss the notification.
Did you plant a tree?
for example in `main` method:
```

  Fimber.plantTree(DebugTree());
```

**Comment by alexZaicev** [comment]
I have realized I need to surround my main method with

> Fimber.plantTree(DebugTree())
> and
> Fimber.unplantTree(DebugTree.elapsed());
