### ISSUE TITLE
Please update dependencies "fimber" to 0.4.0

### ISSUE THREAD

**Issue by dokinkon** [magillus/flutter-fimber#70]
Looks like fimber and fimber-io were updated to 0.4.0, but flutter_fimber stays on "0.3.2". Therefore I can't integrate both fimber-io and flutter-fimber in my project. Thanks.

**Comment by magillus** [comment]
that might be my overlook with deploy - will double check soon and update.

Thank you for reporting.

**Comment by magillus** [comment]
And 0.4.0 is released @dokinkon

**Comment by dokinkon** [comment]
Got it. Thank your kindly and quickly reply.
