### ISSUE TITLE
Dupplicates log levels in Fimber._muteLevels list

### ISSUE THREAD

**Issue by saidlp** [magillus/flutter-fimber#73]
hi, and thanks for a great library!
I just ran into what might be a little issue here: I couldn't get the Verbose level to show, so running the debugger, I found out I had two "V" String objects into the Fimber._muteLevels list... I probably did miss something while handling the list, but it might be an idea anyway to protect the list agains duplicates (check if not already present when adding for ex).

Best regards, and thanks a lot again, keep up good work!

**Comment by magillus** [comment]
Hello thank you for feedback.
You might be right if your code to add "V" to mute levels multiple times the `remove` method on the List only removes first occurrance.

**Comment by saidlp** [comment]
Hi, and thank you for your fast reply.
Yes, I reckon that's what happened: my code unmuted "V" several times, and then unmuting it wouldn't work - unless I unmuted it as many times. Could be an idea to check if a level is already present in the _muteLevels list before adding it to prevent duplicates.
Many thanks again for a great little lib. I really like it!

**Comment by magillus** [comment]
Resolved in 0.4.2!
