### ISSUE TITLE
Log is cut on terminal

### ISSUE THREAD

**Issue by danielgomezrico** [magillus/flutter-fimber#89]
When the log is big then it is cut from the terminal and you can't see the full output.

```dart
debugPrint(someSuperLongString, wrapWidth: 1024);
```

One one to overcome this is by using another function by logging 
https://github.com/flutter/flutter/issues/22665#issuecomment-506687219.

Is there any way to overcome this?

**Comment by magillus** [comment]
`flutter_fimber' have a `DebugBufferTree` that uses that method, but I see that we need wrap option.

Thank you for reporting.
