### ISSUE TITLE
Import shows two options

### ISSUE THREAD

**Issue by danielgomezrico** [magillus/flutter-fimber#91]
Hi

Intellij advise me to add two possible imports when using `Fimber.`:

```dart
// 1.
import 'package:fimber/fimber_base.dart';
// 2.
import 'package:fimber/fimber.dart';
```

Which one should we choose? and why?

**Comment by magillus** [comment]
Hello, use `import 'package:fimber/fimber.dart';`

**Comment by danielgomezrico** [comment]
@magillus but with that I am importing things that I will need? I mean, if I import only the base it still works...

**Comment by magillus** [comment]
I fixed the multiple imports prompts on version 0.6.0+ I noticed my mistake when creating files inside the package.
