### ISSUE TITLE
Fimber.d showing output twice.

### ISSUE THREAD

**Issue by dspells** [magillus/flutter-fimber#92]
This may be more of a question than an issue with Fimber, but I'm not sure.

I'm using Android Studio 4.1.2

I'm seeing the output twice in the 'Run' console of Android Studio. Here is a simple example...
`D/BladePortsHolder._refresh(23318): refreshing`
`I/flutter (23318): 0:07:30.746915	D	BladePortsHolder._refresh:	 refreshing`

The first output has the function name and my output.
The second output has the same thing with flutter, a numeric id and the time.
Perhaps I just need to change a setting? I would like to see only one output. Doubling the output

I'm using the current Beta channel of flutter but I don't think that matters. Channel beta, 1.26.0-17.3.pre. Dart version 2.12.0 (build 2.12.0-259.8.beta).
  flutter_fimber: ^0.4.4

Here is my main function
`void main() async {
  Fimber.plantTree(FimberTree(useColors: true));
  Fimber.plantTree(DebugTree.elapsed());
  await HiveHelper.init();
  AppState.instance = AppState();
  await AppState.instance.init();

  runApp(IntellaViewMobileApp());
}`

**Comment by magillus** [comment]
Hello,
You attached both trees (DebugTree, FimberTree), so you log twice to console.
Pick one of them. In flutter use the FimberTree

(Apologize short message, written on phone)

**Comment by magillus** [comment]
After seeing the example app code recently  I see how you got 2 added trees, you added based on example. I will update the comments on the example code so developer can choose of the trees.
